###### VARIABLES YOU SHOULD CONFIGURE FOR YOUR DEPLOYEMNT
###### OR PASS as "-e" args to ansible-playbook command

# Stuff that should come from elsewhere, but including here to make things work locally
guid: nstephan
opentlc_user: nate-redhat.com
admin_user: nate-admin # needed to give access to new projet and will be removed later
user_pub_key: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4LIAh+LeqBsODfR9YMqyk6E74hE9/FzyDsBf7pukER7alw99JLySZFeO7hL0COXrQlbweVDTwbU5GJrLSbUQZvgVOIbH/roAwMBjzuwdh7ibLyxZNdJs/6gLifWUXSmaj/JKXCr2Lg+527wRfePY+1mXJNMc+cbrezWoUpNlhw3D1NrcJnxldmRn6Rw0jnQdaz1PtAgMfX4Xftr9RV0GggtAwCGjViBK6WM+Fkfp4hT0EMVoCtwvhmEIzeaYaHofit3pW/KONp1DG/OisojUcDuQ6S7i5Mt35N1LmzR06ED4c8kOLMaqZ7UDupFOoILL/vqayVjL67trgcsTcJXI5
output_dir: /Users/nstephan/gpte/tests
env_type: ocp4-disconnected-osp-lab

cloud_provider: osp


clientvm_instance_type: m1.small
clientvm_instance_image: rhel-guest-7.7

utilityvm_instance_type: m1.small
utilityvm_instance_image: rhel-guest-7.7

# DNS servers will be provided to the subnet and
# injected into the instances on that subnet.
# This should be a comma separated list if more than one
dns_nameservers: 169.45.246.132

# Quotas to set for new project that is created
quota_num_instances: 10
quota_num_cores: 32
quota_memory: 131072 # in MB
quota_num_volumes: 25
quota_volumes_gigs: 500
#quota_loadbalancers: #when Octavia is available
#quota_pool: #when Octavia is available
quota_networks: 3
quota_subnets: 3
quota_routers: 3
quota_fip: 4
quota_sg: 5
quota_sg_rules: 75

# Security groups and associated rules
security_groups:
  - name: bastion_sg
    description: Bastion security group allows basic ICMP and SSH ingress and egress to *
    rules:
    - protocol: ICMP
      direction: ingress
    - protocol: TCP
      direction: ingress
      port_range_min: 22
      port_range_max: 22
      remote_ip_prefix: 0.0.0.0/0
    - protocol: TCP
      direction: egress
      remote_ip_prefix: 0.0.0.0/0
  - name: utility_sg
    description: Utility security group allows SSH from bastion and egress to *
    rules:
    - protocol: TCP
      direction: ingress
      port_range_min: 22
      port_range_max: 22
      remote_group_id: bastion_sg


# Authenication for OpenStack in order to create the things
osp_auth_url: 
osp_auth_username: 
osp_auth_password:
osp_auth_cloud:
osp_auth_project_domain: #usually set to "default"
osp_auth_user_domain: #usually set to "default"

# PROBABLY SHOULDN'T BE CHANGING THIS

provider_network: external

# Instances to be provisioned in new project
instances:
  - name: "clientvm"
    count: 1
    unique: yes
    alt_name: bastion
    image_id: "{{ clientvm_instance_image }}"
    floating_ip: yes
    flavor:
      "ec2": "{{ clientvm_instance_type }}"
      "osp": "{{ clientvm_instance_type }}"
    tags:
      - key: "AnsibleGroup"
        value: "bastions,clientvms"
    rootfs_size: 30
    security_groups:
      - bastion_sg
  
  - name: "utiltiyvm"
    count: 1
    image_id: "{{ utilityvm_instance_image }}"
    floating_ip: no
    flavor: 
      "ec2": "{{ utilityvm_instance_type }}"
      "osp": "{{ utilityvm_instance_type }}"
    security_groups:
      - utility_sg