- name: Step 002 Post Infrastructure
  hosts: localhost
  connection: local
  become: false
  tags:
  - step002
  - post_infrastructure
  tasks:
    - name: Create DNS zone
      debug:
        msg: Currently using {{ ocp_cluster_dns_zone }} on server {{ ocp_cluster_dns_server }}

    - name: Add DNS entry for clientVM
      nsupdate:
        server: "{{ ocp_cluster_dns_server }}"
        zone: "{{ ocp_cluster_dns_zone }}"
        record: "{{ item }}.{{ guid }}"
        type: A
        value: "{{ hot_output | json_query(query) }}"
        # key_name:
        # key_secret:
      vars:
        query: "stack.outputs[?output_key=='{{ item }}'].output_value"
      with_items:
        - "ocp_api_fip"
        - "ocp_ingress_fip"
        - "clientvm_fip"

#     - name: Add DNS entry for OpenShift API

#     - name: Add DNS entry for OpenShift ingress

# - name: Step 002 Post Infrastructure
#   hosts: clientvms
#   become: true
#   tags:
#   - step002
#   - post_infrastructure
#   tasks:
#     - name: Create clouds.yaml file on bastion