- name: Step 002 Post Infrastructure
  hosts: localhost
  connection: local
  become: false
  tags:
  - step002
  - post_infrastructure
  tasks:
    - debug:
        msg: "Dummy placeholder task"
    
    - name: Add DNS entries for OpenShift
      nsupdate:
        server: "{{ ocp_cluster_dns_server }}"
        zone: "{{ ocp_cluster_dns_zone }}"
        record: "{{ item.dns }}.{{ guid }}" #".{{ ocp_cluster_dns_zone }}"
        type: A
        ttl: 5
        value: "{{ hot_output | json_query(query) }}"
        key_name: red.osp.opentlc.com
        key_secret: "7pJWaQeTY0qqP2i2E/LSYJF+h3P+SUuFswUWD3bMDrnyYtllM1nZEqfg GEtyWwQ+fsjxrTMTjSnJmMR0zm2lEA=="
      vars:
        query: "stack.outputs[?output_key==`{{ item.name | to_json }}`].output_value"
      with_items:
        - { name: "ocp_api_fip", dns: "api" }
        - { name: "ocp_ingress_fip", dns: "apps" }