- debug:
    var: osp_project_creation.project.name

- name: Gather instance facts
  os_server_facts:
    server: "*"
    # filters:
    #   project: "{{ project_tag }}"
  register: osp_facts
  # tags:
  #   - create_inventory
  #   - must

- name: debug osp_facts
  debug:
    var: osp_facts

- set_fact:
    stack_tag: "{{env_type | replace('-', '_')}}_{{guid}}"
  tags:
    - create_inventory
    - must

# Find the bastion
- name: Find the bastion in this batch of host
  set_fact:
    local_bastion: "{{ item.name }}"
  when:
    - item.status != 'terminated'
    - '"bastions" in item.metadata.AnsibleGroup'
  with_items: "{{ osp_facts.ansible_facts['openstack_servers'] }}"
  loop_control:
    label: "{{item.name | default(item.name)}}"
  ignore_errors: yes
  tags:
    - create_inventory
    - must

- add_host:
    name: "{{ item.name }}"
    groups:
      - "tag_Project_{{stack_tag}}"
      - "tag_{{stack_tag}} | default('unknowns')}}"
      - "tag_{{stack_tag}}_ostype | default('unknown')}}"
      - "{{item.metadata.ostype | default('unknowns')}}"
    ansible_user: cloud-user
    remote_user: cloud-user
    # ansible_ssh_private_key_file: "{{item['key_name']}}"
    # key_name: "{{item['key_name']}}"
    state: "{{item['status']}}"
    instance_id: "{{ item.id }}"
    # public_dns_name: "{{item['public_dns_name']}}"
    # private_dns_name: "{{item['private_dns_name']}}"
    private_ip_address: "{{item['private_v4']}}"
    public_ip_address: "{{item['public_v4']}}"
    image_id: "{{item.image.id}}"
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    bastion: "{{ local_bastion | default('') }}"
  when: item.status != 'terminated'
  with_items: "{{ osp_facts.ansible_facts['openstack_servers'] }}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - create_inventory
    - must

- add_host:
    name: "{{item.name}}"
    groups: "{{item.metadata.AnsibleGroup}}"
  with_items: "{{ osp_facts.ansible_facts['openstack_servers'] }}"
  when: item.status != 'terminated'
  loop_control:
    label: "{{item.name}}"
  tags:
    - create_inventory
    - must

- name: debug hostvars
  debug:
    var: hostvars
    verbosity: 2

- name: debug groups
  debug:
    var: groups
    verbosity: 2
