---
- name: Step 001.1 Deploy Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step001
    - step001.1
    - deploy_infrastructure
  tasks:
    - name: Run infra-template-generate Role
      import_role:
        name: infra-template-generate

    - name: Run infra-template-create Role
      import_role:
        name: infra-template-create